
name: Health check

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '30 10 * 09 *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://full-stack-open-pokedex1.herokuapp.com/health
          max-attempts: 3
          retry-delay: 5s